name: sahyatri
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.2

  cupertino_icons: ^1.0.8
  intl: ^0.19.0
  http: ^1.3.0
  flutter_spinkit: ^5.1.0
  

dev_dependencies:
  flutter_native_splash: ^2.3.5
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

flutter_native_splash:
  color: "#ffffff"
  image: assets/images/bus_logo.png
  branding: assets/images/sahyatri_text.png
  android: true
  ios: false
  web: false


 